[versions]
# 插件版本
agp = "8.13.0"
kotlin = "2.2.0"

# AndroidX核心库
androidxCore = "1.12.0"
androidxAppCompat = "1.6.1"
androidxActivity = "1.8.0"
androidxConstraintlayout = "2.1.4"
androidxRecyclerview = "1.3.2"
androidxNavigation = "2.7.7"

# 第三方库
material = "1.12.0"
gson = "2.8.9"
okhttp = "4.9.3"
volley = "1.2.1"
markwon = "4.6.2"

# 测试库
junit = "4.13.2"
junitExt = "1.1.5"
espressoCore = "3.5.1"
coreKtx = "1.10.1"

[libraries]
# AndroidX核心库
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidxActivity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerview" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }

# 第三方库
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
markwon-core = { group = "io.noties.markwon", name = "core", version.ref = "markwon" }

# 测试库
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }